apiVersion: v1
kind: Service
metadata:
  name: patrimonial-k8s-service
spec:
  selector:
    app: patrimonial-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
  type: LoadBalancer
